target 'TiempoDeEstudio' do
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for Capsull
pod 'SwiftSpreadsheet', '~> 1.0'
pod 'SpreadsheetView'
pod 'Canvas'
end
